name: Open PR on Schema Update

on:
  repository_dispatch:
    types: [update-schema]

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Dummy File for Testing (Optional)
        run: |
          echo "Test file for PR" > test.txt

      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Test: Update based on new schema"

      - name: Push Changes
        run: git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TEST_GITHUB_TOKEN }}
          commit-message: test
          title: 'New Update'
          branch: create-pr-for-update  # This is the branch that will be created for the PR
